### ISSUE TITLE
No soup for you - crash in TEFirePit.java when making a soup with food that has no nutrition

### ISSUE THREAD

**Issue by Broam** [TerraFirmaCraft/TerraFirmaCraft#1552]
Create soup using the fire pit using 1-5 fish, and only fish. Salmon, Pufferfish, Cod are interchangeable. When the soup is done, crash. Affects both SMP and SSP.

Using TNFC 1.12.25 modpack. Fish are 1% water but no nutritional value until cooked. A cursory look at the code makes me think that because no nutrient is available, none is set - and that's where the NPE comes from.

Stack trace:

java.lang.NullPointerException
    at net.dries007.tfc.objects.te.TEFirePit.writeToNBT(TEFirePit.java:492)
    at net.dries007.tfc.objects.te.TEBase.getUpdateTag(TEBase.java:46)
    at net.dries007.tfc.objects.te.TEBase.getUpdatePacket(TEBase.java:35)
    at net.minecraft.server.management.PlayerChunkMapEntry.sendBlockEntity(PlayerChunkMapEntry.java:288)
    at net.minecraft.server.management.PlayerChunkMapEntry.update(PlayerChunkMapEntry.java:250)
    at net.minecraft.server.management.PlayerChunkMap.tick(SourceFile:115)
    at net.minecraft.world.WorldServer.tick(WorldServer.java:227)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:748)

**Comment by Broam** [comment]
This requires some mod config, but in short - the "fish" I was using have no nutrition assigned, being Minecraft Raw Fish not TFC Raw Fish. The crash bug is on the soup pot cooking items that have no nutrition after they have been allowed in using an additional mod. It's not an error per se in TFC, but the NBT writing code does have an NPE.
