### ISSUE TITLE
Strange crash

### ISSUE THREAD

**Issue by Exzept1on** [TerraFirmaCraft/TerraFirmaCraft#1715]
**Describe the bug**
I'm playing on a server with TFC and its addons like Dynamic Trees TFC and TFCTECH and TFC-metalllum. And sometimes the server crashes with this error. This happens randomly, I still can't figure out why, to write here.

log:
net.minecraft.util.ReportedException: Ticking entity
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:988) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:461) ~[nz.class:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:858) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:730) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NoSuchMethodError: net.minecraft.entity.item.EntityItem.func_174872_o()I
at net.dries007.tfc.objects.items.itemblock.ItemBlockSaplingTFC.onEntityItemUpdate(ItemBlockSaplingTFC.java:19) ~[ItemBlockSaplingTFC.class:?]
at net.minecraft.entity.item.EntityItem.onUpdate(EntityItem.java:93) ~[acl.class:?]
at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:2340) ~[amu.class:?]
at net.minecraft.world.World.updateEntity(World.java:2294) ~[amu.class:?]
at net.minecraft.world.World.redirect$zbg000$updateEntity(World.java:4513) ~[amu.class:?]
at net.minecraft.world.World.updateEntities(World.java:2076) ~[amu.class:?]
at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:852) ~[oo.class:?]
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:981) ~[MinecraftServer.class:?]
... 4 more

**To Reproduce**
I do not know, since at least 4 people play on the server and it happens randomly or not, I can not find out.

**Meta Info**
 - TFC Version: 1.7.13.161
 
 I understand that there is little information, but perhaps someone knows about such a problem.
 
 **Or you can at least explain why this can happen**

**Comment by HeartyYF** [comment]
Please try to use the latest release. Some days earlier we found it too and reported it on discord because at first we thought it may be due to some conflicts between mods, but it turned out that it's a bug, and in cb3991498cd73383c3b81790d6d42894e8e974b8 Rongmario fixed that.

**Comment by Exzept1on** [comment]
Wow. Well, I didn't notice, right now I'll check, if everything is fine, I'll close the error. :D

**Comment by alcatrazEscapee** [comment]
Fixed by #1708
