### ISSUE TITLE
worldgen crash exploring in TNFC

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#1737]
[crash-2021-02-24_23.27.48-client.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/6153544/crash-2021-02-24_23.27.48-client.txt)
[latest.log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/6153546/latest.log)

[21:17:30] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception generating new chunk
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:762) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_272]
Caused by: java.lang.IllegalArgumentException: Layer 41 not used.
	at net.dries007.tfc.world.classic.DataLayer.get(DataLayer.java:37) ~[DataLayer.class:?]
	at net.dries007.tfc.world.classic.ChunkGenTFC.loadLayerGeneratorData(ChunkGenTFC.java:369) ~[ChunkGenTFC.class:?]
	at net.dries007.tfc.world.classic.ChunkGenTFC.generateChunk(ChunkGenTFC.java:217) ~[ChunkGenTFC.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:143) ~[on.class:?]
	at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:126) ~[ot.class:?]
	at net.minecraft.server.management.PlayerChunkMap.tick(PlayerChunkMap.java:226) ~[ou.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:227) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) ~[MinecraftServer.class:?]
	... 4 more

**Meta Info**
 - TFC Version: build 175
 - TNFC 12.2.62

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
