### ISSUE TITLE
EntityFallingBlockTFC.getBlock crashed

### ISSUE THREAD

**Issue by komimoe** [TerraFirmaCraft/TerraFirmaCraft#1808]
**Describe the bug**
java.lang.NoSuchFieldError: renderState
at net.dries007.tfc.objects.entity.EntityFallingBlockTFC.func_175131_l(EntityFallingBlockTFC.java:85) ~[EntityFallingBlockTFC.class:?]
at moe.plushie.armourers_workshop.common.handler.DollCraftingHandler.func_72709_b(DollCraftingHandler.java:72) ~[DollCraftingHandler.class:?]
at net.minecraft.world.World.func_72847_b(World.java:1567) ~[amu.class:?]
at net.minecraft.world.WorldServer.func_72847_b(WorldServer.java:1319) ~[oo.class:?]
at net.minecraft.world.World.func_72939_s(World.java:2156) ~[amu.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:744) ~[oo.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:897) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:467) ~[nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:624) [MinecraftServer.class:?]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]

**Comment by alcatrazEscapee** [comment]
This issue does not apply, or has been fixed in the current MC 1.18 versions of TFC, and as MC 1.12 is receiving no more development, it will be closed. If this issue arises again in 1.18, please file a new issue report.
