### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by TheIssueReporter27** [TerraFirmaCraft/TerraFirmaCraft#1864]
Time: 1/22/22 10:25 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraft.client.util.SearchTree.func_194039_a(SourceFile:48)
	at net.minecraft.client.util.SearchTree$$Lambda$4594/1321975945.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:48)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$4633/1250179659.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:604)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.util.SearchTree.func_194039_a(SourceFile:48)
	at net.minecraft.client.util.SearchTree$$Lambda$4594/1321975945.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:48)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$4633/1250179659.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:604)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by alcatrazEscapee** [comment]
There are many things wrong with this, your stacktrace has many errors that point to either something going horribly wrong, very out of date mods, or another root cause and you've omitted the end of the error. Full log required.

**Comment by TheIssueReporter27** [comment]
i have been getting this error now for 3 weeks

**Comment by alcatrazEscapee** [comment]
You have edited the issue with a *completely different stacktrace* that has nothing to do with the first error you posted.

**Comment by TheIssueReporter27** [comment]
I know this is the error i am getting now

**Comment by TheIssueReporter27** [comment]
I don't know what is wrong when my Minecraft crashes

**Comment by TheIssueReporter27** [comment]
can someone help me fix this stupid fucking error it has been fucking with me for 3 weeks now can someone explain how to fix this please I have been not playing modded Minecraft for a long time now and its starting to stress me so much I beat myself up for no reason can someone please help I am sick and tired of this nonsense.

**Comment by Gaelmare** [comment]
Upload your full logs to a site like pastebin, hastebin, gist.github, etc. and put a link here. Otherwise, we can't help.
