### ISSUE TITLE
IGlow can cause crashes on flowing liquids

### ISSUE THREAD

**Issue by Charnuz** [TerraFirmaCraft/TerraFirmaCraft#1923]
[full stack](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/8388925/crash-2022-03-31_06.11.24-server.txt)

```
java.lang.IllegalArgumentException: Tried to get the FluidKey for a fluid [minecraft:flowing_water] which was not present in property fluid / [FluidKey[minecraft:empty], FluidKey[tfc:salt_water], FluidKey[minecraft:water]]
	at net.dries007.tfc.common.fluids.FluidProperty.keyFor(FluidProperty.java:95) ~[%2380!/:?] {re:classloading}
	at net.dries007.tfc.common.entities.IGlow.lambda$tick$0(IGlow.java:78) ~[%2380!/:?] {re:classloading}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.dries007.tfc.common.entities.IGlow.tick(IGlow.java:76) ~[%2380!/:?] {re:classloading}
	at net.dries007.tfc.common.entities.aquatic.Octopoteuthis.tick(Octopoteuthis.java:102) ~[%2380!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.tickNonPassenger(ClientLevel.java:221) ~[forge-1.18.2-40.0.19_mapped_official_1.18.2-recomp.jar%2376!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:tfc.mixins.json:client.ClientLevelMixin,pl:mixin:APP:tfc.mixins.json:client.accessor.ClientLevelAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:486) ~[forge-1.18.2-40.0.19_mapped_official_1.18.2-recomp.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tfc.mixins.json:LevelMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientLevel.lambda$tickEntities$4(ClientLevel.java:203) ~[forge-1.18.2-40.0.19_mapped_official_1.18.2-recomp.jar%2376!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:tfc.mixins.json:client.ClientLevelMixin,pl:mixin:APP:tfc.mixins.json:client.accessor.ClientLevelAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54) ~[forge-1.18.2-40.0.19_mapped_official_1.18.2-recomp.jar%2376!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.tickEntities(ClientLevel.java:201) ~[forge-1.18.2-40.0.19_mapped_official_1.18.2-recomp.jar%2376!/:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:tfc.mixins.json:client.ClientLevelMixin,pl:mixin:APP:tfc.mixins.json:client.accessor.ClientLevelAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.tick(Minecraft.java:1686) ~[forge-1.18.2-40.0.19_mapped_official_1.18.2-recomp.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tfc.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1019) ~[forge-1.18.2-40.0.19_mapped_official_1.18.2-recomp.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tfc.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.run(Minecraft.java:663) ~[forge-1.18.2-40.0.19_mapped_official_1.18.2-recomp.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tfc.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[forge-1.18.2-40.0.19_mapped_official_1.18.2-recomp.jar%2376!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.ForgeClientUserdevLaunchHandler.lambda$launchService$0(ForgeClientUserdevLaunchHandler.java:38) ~[fmlloader-1.18.2-40.0.19.jar%230!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2310!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2310!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2310!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2310!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2310!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2310!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2310!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
```

**Comment by KittenRaee** [comment]
Also getting crashes

[crash-log](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/8393038/crash-2022-03-30_19.46.00-client.txt)

**Comment by Charnuz** [comment]
Easy way to fix this would be to change `keyFor` with `keyForOrEmpty` but that will result in flowing liquids being replaced by air
