### ISSUE TITLE
Crash during world or chunk generation

### ISSUE THREAD

**Issue by xxMrPHDxx** [TerraFirmaCraft/TerraFirmaCraft#210]
I have been playing a build using the latest code just now and create a test world and my world crash after entering a certain chunk.

```
---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 7/28/19 9:13 AM
Description: Exception generating new chunk

java.lang.RuntimeException: Something went wrong in world gen I guess?
	at net.dries007.tfc.world.classic.genlayers.GenLayerSmoothTFC.func_75904_a(GenLayerSmoothTFC.java:54)
	at net.dries007.tfc.world.classic.genlayers.river.GenLayerRiverMixTFC.func_75904_a(GenLayerRiverMixTFC.java:78)
	at net.minecraft.world.biome.BiomeProvider.func_76937_a(BiomeProvider.java:82)
	at net.dries007.tfc.world.classic.ChunkGenTFC.generateRoughTerrain(ChunkGenTFC.java:353)
	at net.dries007.tfc.world.classic.ChunkGenTFC.func_185932_a(ChunkGenTFC.java:179)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.dries007.tfc.world.classic.genlayers.GenLayerSmoothTFC.func_75904_a(GenLayerSmoothTFC.java:54)
	at net.dries007.tfc.world.classic.genlayers.river.GenLayerRiverMixTFC.func_75904_a(GenLayerRiverMixTFC.java:78)
	at net.minecraft.world.biome.BiomeProvider.func_76937_a(BiomeProvider.java:82)
	at net.dries007.tfc.world.classic.ChunkGenTFC.generateRoughTerrain(ChunkGenTFC.java:353)
	at net.dries007.tfc.world.classic.ChunkGenTFC.func_185932_a(ChunkGenTFC.java:179)

-- Chunk to be generated --
Details:
	Location: 3,-28
	Position hash: -120259084285
	Generator: net.dries007.tfc.world.classic.ChunkGenTFC@7f211c34
Stacktrace:
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:143)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: TerraFirmaCraft
	All players: 1 total; [EntityPlayerMP['xxMrPHDxx'/220, l='TerraFirmaCraft', x=-74.84, y=159.00, z=-309.48]]
	Chunk stats: ServerChunkCache: 690 Drop: 269
	Level seed: -3974709960607286932
	Level generator: ID 06 - tfc_classic, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (108,144,252), Chunk: (at 12,9,12 in 6,15; contains blocks 96,0,240 to 111,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 35163 game time, 35163 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 30616 (now: false), thunder time: 112625 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1115845072 bytes (1064 MB) / 1845493760 bytes (1760 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Xmx2G
	IntCache: cache: 2, tcache: 37, allocated: 0, tallocated: 32
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID           | Version      | Source                              | Signature                                |
	|:--------- |:------------ |:------------ |:----------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft    | 1.12.2       | minecraft.jar                       | None                                     |
	| UCHIJAAAA | mcp          | 9.42         | minecraft.jar                       | None                                     |
	| UCHIJAAAA | FML          | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge        | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar       | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | ichunutil    | 7.2.0        | iChunUtil-1.12.2-7.2.0.jar          | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| UCHIJAAAA | jei          | 4.15.0.268   | jei_1.12.2-4.15.0.268.jar           | None                                     |
	| UCHIJAAAA | tfc          | ${version}   | TerraFirmaCraft-MC1.12.2-0.12.0.jar | None                                     |
	| UCHIJAAAA | xaerominimap | 1.16.3       | Xaeros-Minimap-Mod-1.12.jar         | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	TerraFirmaCraft: You are not running an official build. Please do not use this and then report bugs or issues.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['xxMrPHDxx'/220, l='TerraFirmaCraft', x=-74.84, y=159.00, z=-309.48]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by alcatrazEscapee** [comment]
Possibly maybe kinda sorta fixed by e840c1f87d7cfa29b487734397d82ed971912d40
