### ISSUE TITLE
Field Guide is not loading a page 2.1.8

### ISSUE THREAD

**Issue by Gaelmare** [TerraFirmaCraft/TerraFirmaCraft#2157]
```
[10:37:30] [Render thread/ERROR] [patchouli/]: Error compiling book patchouli:field_guide, using empty contents
java.lang.RuntimeException: Error building entry patchouli:the_world/flora
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:98) ~[Patchouli-1.18.2-71.1.jar%2355!/:1.18.2-71.1] {re:classloading}
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?] {}
	at vazkii.patchouli.client.book.BookContentsBuilder.build(BookContentsBuilder.java:94) ~[Patchouli-1.18.2-71.1.jar%2355!/:1.18.2-71.1] {re:classloading}
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:225) ~[Patchouli-1.18.2-71.1.jar%2355!/:1.18.2-71.1] {re:mixin,re:classloading}
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:128) ~[Patchouli-1.18.2-71.1.jar%2355!/:1.18.2-71.1] {re:mixin,re:classloading}
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[Patchouli-1.18.2-71.1.jar%2355!/:1.18.2-71.1] {re:classloading}
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:34) ~[Patchouli-1.18.2-71.1.jar%2355!/:1.18.2-71.1] {re:classloading,re:mixin}
	at net.minecraft.client.multiplayer.ClientAdvancements.handler$zca000$patchouli_onSync(ClientAdvancements.java:1017) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,re:classloading,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorClientAdvancements,pl:mixin:APP:patchouli_xplat.mixins.json:client.MixinClientAdvancements,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientAdvancements.m_104399_(ClientAdvancements.java:57) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,re:classloading,pl:mixin:APP:patchouli_xplat.mixins.json:client.AccessorClientAdvancements,pl:mixin:APP:patchouli_xplat.mixins.json:client.MixinClientAdvancements,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5498_(ClientPacketListener.java:1135) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:51) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,re:mixin}
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:16) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,re:mixin}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tfc.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tfc.mixins.json:client.MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2357!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.80.jar%2351!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%2339!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?] {}
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?] {}
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?] {}
Caused by: java.lang.RuntimeException: Error while loading entry patchouli:the_world/flora page 5
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:250) ~[Patchouli-1.18.2-71.1.jar%2355!/:1.18.2-71.1] {re:classloading}
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.18.2-71.1.jar%2355!/:1.18.2-71.1] {re:classloading}
	... 45 more
Caused by: java.lang.IllegalArgumentException: Failure parsing state matcher
	at vazkii.patchouli.common.multiblock.SerializedMultiblock.deserializeMapping(SerializedMultiblock.java:41) ~[Patchouli-1.18.2-71.1.jar%2355!/:1.18.2-71.1] {re:classloading}
	at vazkii.patchouli.common.multiblock.SerializedMultiblock.deserializeDense(SerializedMultiblock.java:93) ~[Patchouli-1.18.2-71.1.jar%2355!/:1.18.2-71.1] {re:classloading}
	at vazkii.patchouli.common.multiblock.SerializedMultiblock.toMultiblock(SerializedMultiblock.java:103) ~[Patchouli-1.18.2-71.1.jar%2355!/:1.18.2-71.1] {re:classloading}
	at vazkii.patchouli.client.book.page.PageMultiblock.build(PageMultiblock.java:71) ~[Patchouli-1.18.2-71.1.jar%2355!/:1.18.2-71.1] {re:classloading}
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:247) ~[Patchouli-1.18.2-71.1.jar%2355!/:1.18.2-71.1] {re:classloading}
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.18.2-71.1.jar%2355!/:1.18.2-71.1] {re:classloading}
	... 45 more
Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Block tfc:plant/spanish_moss does not have property 'hanging' at position 23: ...nish_moss[<--[HERE]
```

**Comment by Gaelmare** [comment]
Error made it seem much more serious than it is. Whole guide and flora entry aren't empty, whew.

**Comment by alcatrazEscapee** [comment]
Cannot reproduce with the TFC book. That page looks like it was [removed](https://github.com/TerraFirmaCraft/TerraFirmaCraft/commit/93e687b7f824a220f2336f11df42c38a2607ba5a#diff-82e7589a9c3ffaf04b4c9c4d9da585d05e29dd25d1288a99807d4f120ad68a12) in the same commit which removed the property, so there shouldn't be any mismatch there. It also looks like you're loading the wrong entry (`patchouli:the_world/flora` is from a book in the `patchouli` namespace, aka one loaded from a modpack, not the TFC one).

It looks like you're loading an old version of the book from a local directory in a new version.

**Comment by Gaelmare** [comment]
Busted, error goes away on clean install. Sorry.
