### ISSUE TITLE
Server with custom map crashing due to terrain generation issues

### ISSUE THREAD

**Issue by xXHoraitoNelsonXx** [TerraFirmaCraft/TerraFirmaCraft#2522]
Hello!

Recently, I started an MC server using a slightly modified version of the Auto TFC modpack. I am also using a rather large custom TFC map, 10k by 10k blocks. For a while, the server ran smoothly, however after a few days, it began randomly crashing. After talking to my server host's support team, and ruling out issues with the server resources, we found this in the crash report:

Time: 10/20/23, 12:53 AM
Description: Exception ticking world

java.lang.NullPointerException: Exception ticking world
    at java.util.Objects.requireNonNull(Objects.java:209) ~[?:?] {re:mixin}
    at net.dries007.tfc.world.chunkdata.ChunkData.getRockData(ChunkData.java:107) ~[TerraFirmaCraft-Forge-1.18.2-2.2.27.jar%2359!/:2.2.27] {re:classloading}
    at net.dries007.tfc.common.blocks.plant.PlantRegrowth.placeRisingRock(PlantRegrowth.java:124) ~[TerraFirmaCraft-Forge-1.18.2-2.2.27.jar%2359!/:2.2.27] {re:classloading}
    at net.dries007.tfc.common.blocks.soil.ConnectedGrassBlock.m_7455_(ConnectedGrassBlock.java:154) ~[TerraFirmaCraft-Forge-1.18.2-2.2.27.jar%2359!/:2.2.27] {re:classloading}
    at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60735_(BlockBehaviour.java:681) ~[server-1.18.2-20220404.173914-srg.jar%2364!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:radium.mixins.json:ai.pathing.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:block.flatten_states.AbstractBlockStateMixin,pl:mixin:APP:radium.mixins.json:chunk.block_counting.AbstractBlockStateMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:starlight.mixins.json:common.blockstate.BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}

We were rather confused by this, as it seemed to be referring to generating to generating new chunks. I may very well be wrong about that, as I am not too familiar with the more technical side of Minecraft, however that was the best conclusion we came up with. What doesn't make sense to me is the fact that the game seems to be trying to generate new TFC chunks, despite the fact that A) The world is custom, and should only be generating custom chunks, and B) Even the area outside the map edge is just normal MC generation.

The only thing we could come up with was that it was an issue with the mod's world generation, perhaps when used with a custom map. As far as I am aware, (Correct me if I am wrong) no one has tried to make a custom map for TFC before, so this issue could very well be because of that. 

Full Crash Report: 
[FullCrashReport.txt](https://github.com/TerraFirmaCraft/TerraFirmaCraft/files/13059222/FullCrashReport.txt)

Modpack:
https://drive.google.com/file/d/1RLKu4_xfzPNEdlOz5HXZWVPanV2-MKIR/view?usp=sharing

The Map:
https://drive.google.com/file/d/1kI2ObygJtKgqDD83UemL3VyP_J-8qEXa/view?usp=sharing

I hope that this issue isn't one which takes too long to solve, as I have been working on this server all summer.

**Comment by alcatrazEscapee** [comment]
TFC is attempting to query chunk data, which is set upon TFC's world generation. Given you said you were using a custom map, I'm assuming that means _not_ generated by TFC, and you haven't written or generated a passable shim of this data, meaning it straight up doesn't exist. Since we rely on this for a number of things (climate, rock information, hydration, etc), your world may be broken in other ways.

In this case the _crash_ is caused by TFC trying to spawn new rocks after a while on existing generated chunks. Obviously, this won't work if TFC did not generate the rock types in those chunks first.

You can disable the feature of TFC causing the crash by setting in the server config, `grassSpawningRocksChance=0`
