### ISSUE TITLE
maybe compatibility issues between SKDS and Terrafirmacraft [1.18.2forge]

### ISSUE THREAD

**Issue by wglpython** [TerraFirmaCraft/TerraFirmaCraft#2587]
hey bro,i have question
In the TFC (Terrafirmacraft) mod, blocks of type "tfc:rock/spike/quartize" do not have the boolean property "waterlogged."
When "skds" attempts to perform this operation, it will result in an infinite loop.
`[22:18:42] [SKDS-Worker-1/ERROR]: Exeption while executing task
java.lang.IllegalArgumentException: Cannot set property BooleanProperty{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{tfc:rock/spike/quartzite}
at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:117) ~[client-1.18.2-20220404.173914-srg.jar%23164!/:?]
at net.skds.wpo.fluidphysics.FFluidStatic.getUpdatedState(FFluidStatic.java:111) ~[water_physics_overhaul-1.18.2-0.3.0.jar%23158!/:0.3.0]
at net.skds.wpo.fluidphysics.FFluidBasic.getUpdatedState(FFluidBasic.java:334) ~[water_physics_overhaul-1.18.2-0.3.0.jar%23158!/:0.3.0]
at net.skds.wpo.fluidphysics.FFluidDefault.execute(FFluidDefault.java:58) ~[water_physics_overhaul-1.18.2-0.3.0.jar%23158!/:0.3.0]
at net.skds.wpo.fluidphysics.FFluidBasic.run(FFluidBasic.java:129) ~[water_physics_overhaul-1.18.2-0.3.0.jar%23158!/:0.3.0]
at net.skds.wpo.fluidphysics.FluidTask$DefaultTask.run(FluidTask.java:66) ~[water_physics_overhaul-1.18.2-0.3.0.jar%23158!/:0.3.0]
at net.skds.core.multithreading.UniversalWorkerThread.takeTasksStack(UniversalWorkerThread.java:79) [skds_core-1.18.2-0.3.0.jar%23144!/:0.3.0]
at net.skds.core.multithreading.UniversalWorkerThread.run(UniversalWorkerThread.java:51) [skds_core-1.18.2-0.3.0.jar%23144!/:0.3.0]
[22:18:42] [Render thread/WARN]: Unable to parse the boolean system property 'java.net.preferIPv6Addresses':system - using the default value: false

`
I would greatly appreciate it if you could try to resolve the issue.

**Comment by wglpython** [comment]
https://github.com/Felicis/SKDS-Core thats 1.18.2skds

**Comment by alcatrazEscapee** [comment]
Yes, we use a custom fluid-logging implementation that allows our blocks to have lava, water, or salt water-logging. That means we don't use the vanilla `WATERLOGGED` property. 

If "skds" tries something that should be obviously wrong (they can check for the presence of the waterlogged property), and enters an infinite loop, that's a bug in their mod. You should report this to the author of that mod, there's nothing we can realistically change here, nor should we have to, "skds" is trying to do something and failing.
