### ISSUE TITLE
Error while crafting tools

### ISSUE THREAD

**Issue by deferstudio** [TerraFirmaCraft/TerraFirmaCraft#2622]
Text error:

[20:05:03] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerClickPacket@cbb5777, suppressing error
java.lang.IllegalArgumentException: Recipe must have non-AIR result.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.0.1-jre.jar%2328!/:?] {}
        at org.bukkit.inventory.ShapedRecipe.<init>(ShapedRecipe.java:45) ~[?:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:18) ~[?:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftShapedRecipe.<init>(CraftShapedRecipe.java:22) ~[?:?] {re:classloading}
        at net.minecraft.world.item.crafting.ShapedRecipe.toBukkitRecipe(ShapedRecipe.java:62) ~[?:?] {re:classloading}
        at net.minecraft.world.item.crafting.ShapedRecipe.toBukkitRecipe(ShapedRecipe.java:29) ~[?:?] {re:classloading}
        at org.bukkit.craftbukkit.v1_18_R2.inventory.CraftInventoryCrafting.getRecipe(CraftInventoryCrafting.java:121) ~[?:?] {re:classloading}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerGamePacketListenerImpl.java:2132) ~[?:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[?:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[?:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:26) ~[?:?] {re:classloading}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[?:?] {re:classloading}
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:157) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?] {re:classloading}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:1109) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:139) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:131) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1092) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1086) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:140) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1072) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:958) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:263) ~[?:?] {re:classloading,pl:accesstransformer:B}
        at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

**Comment by eerussianguy** [comment]
Can't use TFC with plugins.
