### ISSUE TITLE
Some recipes of pot can't be viewed in JEI

### ISSUE THREAD

**Issue by ghost** [TerraFirmaCraft/TerraFirmaCraft#2712]
Game version: 1.20.1
TFC Version 3.2.3
Forge: 47.2.20, 47.2.30 

The recipes of pot that input item less than output item can't be viewed in JEI.
This only occurs in version 3.2.3.

**Comment by alcatrazEscapee** [comment]
What are you talking about? Please explain the issue you're having.

**Comment by ghost** [comment]
Maybe what I said  has some errors. The issue is about JEI. I did some tasts,  the recipes like this, the total count of input _ingredients_ is 1, which is less than or not equal to the total count of _item_output_, can still run well, but they can not be viewed with JEI in version 3.2.3: 
![2024-05-25 205435](https://github.com/TerraFirmaCraft/TerraFirmaCraft/assets/168053784/dd295457-2a54-484d-9085-711b3eec0d54)
This made me mistakenly think that the recipe was invalid. 
These recipes can be viewed with JEI in previous versions, thus I had to take the photo of JEI in version 3.2.2.

**Comment by PancakeInvaders2** [comment]
to add some more information on this issue, here's the jei error log:

[26mai2024 13:52:09.358] [Render thread/ERROR] [mezz.jei.library.util.IngredientSupplierHelper/]: Found a broken recipe, failed to setRecipe with RecipeLayoutBuilder: Firmalife firmalife:pot/tomato_sauce class net.dries007.tfc.common.recipes.SimplePotRecipe

The recipe works in the pot, it just doesn't get rendered in JEI

Here's the recipe's json:

> { 
        "\_\_comment\_\_":"This file was automatically created by mcresources",
        "type":"tfc:pot",
        "ingredients":[
            {"type":"tfc:not_rotten","ingredient":{"item":"tfc:food/tomato"}},
            {"item":"tfc:powder/salt"},
            {"type":"tfc:not_rotten","ingredient":{"item":"tfc:food/garlic"}}
        ],
        "fluid_ingredient":{"ingredient":"minecraft:water","amount":100},
        "duration":2000,
        "temperature":300,
        "item_output":[
            {"item":"firmalife:food/tomato_sauce"},
            {"item":"firmalife:food/tomato_sauce"},
            {"item":"firmalife:food/tomato_sauce"},
            {"item":"firmalife:food/tomato_sauce"},
            {"item":"firmalife:food/tomato_sauce"}
        ]
    }

**Comment by alcatrazEscapee** [comment]
Linked duplicate has additional information, copied here, there's a JEI log for this recipe:

```
[30May2024 20:55:38.227] [Render thread/ERROR] [mezz.jei.library.util.IngredientSupplierHelper/]: Found a broken recipe, failed to setRecipe with RecipeLayoutBuilder: Firmalife firmalife:pot/tomato_sauce class net.dries007.tfc.common.recipes.SimplePotRecipe

java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:361) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
	at net.dries007.tfc.compat.jei.category.SimplePotRecipeCategory.setRecipe(SimplePotRecipeCategory.java:72) ~[TerraFirmaCraft-Forge-1.20.1-3.2.3.jar%23187!/:3.2.3]
	at net.dries007.tfc.compat.jei.category.SimplePotRecipeCategory.setRecipe(SimplePotRecipeCategory.java:29) ~[TerraFirmaCraft-Forge-1.20.1-3.2.3.jar%23187!/:3.2.3]
	at mezz.jei.library.util.IngredientSupplierHelper.getIngredientSupplier(IngredientSupplierHelper.java:22) ~[jei-1.20.1-forge-15.3.0.4.jar%23179!/:15.3.0.4]

```
