### ISSUE TITLE
Exception generating chunk with Distant Horizons (server fork)

### ISSUE THREAD

**Issue by 7ERr0r** [TerraFirmaCraft/TerraFirmaCraft#2764]
https://gitlab.com/s809/distant-horizons/-/wikis/home

MC 1.20.1
TerraFirmaCraft-Forge-1.20.1-3.2.7

```
[19:21:40] [DH-World Gen Thread[0]/WARN] [Di.fo.co.se.di.co.wr.wo.st.StepFeatures/]: Unexpected issue when generating features for chunk at pos [C[-61,815]], error: [Biome: 57].
java.lang.NullPointerException: Biome: 57
        at java.util.Objects.requireNonNull(Objects.java:340) ~[?:?] {re:mixin}
        at net.dries007.tfc.world.biome.TFCBiomes.getExtensionOrThrow(TFCBiomes.java:87) ~[TerraFirmaCraft-Forge-1.20.1-3.2.7.jar%23107!/:3.2.7] {re:classloading}
        at net.dries007.tfc.world.TFCChunkGenerator.m_213609_(TFCChunkGenerator.java:348) ~[TerraFirmaCraft-Forge-1.20.1-3.2.7.jar%23107!/:3.2.7] {re:classloading}
        at loaderCommon.forge.com.seibel.distanthorizons.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:85) ~[DistantHorizons-forge-2.1.3-a-dev-1.20.1.jar%23104!/:2.1.3-a-dev] {re:classloading}
        at loaderCommon.forge.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:787) ~[DistantHorizons-forge-2.1.3-a-dev-1.20.1.jar%23104!/:2.1.3-a-dev] {re:classloading}
        at loaderCommon.forge.com.seibel.distanthorizons.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:509) ~[DistantHorizons-forge-2.1.3-a-dev-1.20.1.jar%23104!/:2.1.3-a-dev] {re:classloading}
        at loaderCommon.forge.com.seibel.distanthorizons.common.wrappers.worldGeneration.GenerationEvent.lambda$startEvent$0(GenerationEvent.java:95) ~[DistantHorizons-forge-2.1.3-a-dev-1.20.1.jar%23104!/:2.1.3-a-dev] {re:classloading}
        at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?] {}
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?] {}
        at java.lang.Thread.run(Thread.java:1570) ~[?:?] {}


```

**Comment by 7ERr0r** [comment]
Looks like distant chunks generate but they are less populated.
I don't know if lack of trees in the distance is due to an exception thrown.

![image](https://github.com/user-attachments/assets/fe3a8e84-177c-4ccd-a52f-7f2946e968fc)

**Comment by alcatrazEscapee** [comment]
`Biome: 57` is a mistake because I used the wrong method for debugging, but my _firm guess_ is that's corresponding to a vanilla biome ID. If DH is trying to generate chunks that somehow contain vanilla biomes, with a TFC chunk generator, this will crash, and there's nothing we can do about it.

**Comment by Mqrius** [comment]
I had this same issue with a dedicated server for TerraFirmaGreg, and I solved it by telling Distant Horizons to generate full chunks instead of just terrain/biome features. It then uses the full chunk to make its LODs, avoiding any mod incompatibilities.
`/dh config generation.mode INTERNAL_SERVER`

After that you can pregenerate chunks with `/dh pregen start minecraft:overworld 0 0 32`
Replace `0 0` with your home's coordinates. Replace `32` with something big, like `256` for a 4000 block radius, though this will take up to an hour depending on your PC. Replace `minecraft:overworld` with `minecraft:the_nether` for the nether (or the Beneath in TerraFirmaGreg).

This Issue can be closed because there is nothing TFC needs to do about this, but I wanted to record the answer here because this is the only result on google for this specific issue.
