### ISSUE TITLE
1.20.1 crashes on startup

### ISSUE THREAD

**Issue by RenClayd** [TerraFirmaCraft/TerraFirmaCraft#2810]
Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.46]

textures.minecraft.net resolves to:
    [13.107.246.46]

api.mojang.com resolves to:
    [13.107.246.46]

Minecraft folder is:
C:/Users/User/Desktop/UltimMC/instances/terra firma craft/.minecraft

Java path is:
C:/Program Files/Java/jdk-17/bin/javaw.exe

Checking Java version...
Java is version 17.0.12, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/User/Desktop/UltimMC/instances/terra firma craft/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/User/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  C:/Users/User/Desktop/UltimMC/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  C:/Users/User/Desktop/UltimMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  C:/Users/User/Desktop/UltimMC/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  C:/Users/User/Desktop/UltimMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/User/Desktop/UltimMC/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  C:/Users/User/Desktop/UltimMC/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  C:/Users/User/Desktop/UltimMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/User/Desktop/UltimMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  C:/Users/User/Desktop/UltimMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/User/Desktop/UltimMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/User/Desktop/UltimMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/User/Desktop/UltimMC/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  C:/Users/User/Desktop/UltimMC/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  C:/Users/User/Desktop/UltimMC/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  C:/Users/User/Desktop/UltimMC/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  C:/Users/User/Desktop/UltimMC/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  C:/Users/User/Desktop/UltimMC/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  C:/Users/User/Desktop/UltimMC/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  C:/Users/User/Desktop/UltimMC/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  C:/Users/User/Desktop/UltimMC/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc5/ForgeWrapper-mmc5.jar
  C:/Users/User/Desktop/UltimMC/libraries/cpw/mods/securejarhandler/2.1.10/securejarhandler-2.1.10.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/ow2/asm/asm/9.7/asm-9.7.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/ow2/asm/asm-commons/9.7/asm-commons-9.7.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/ow2/asm/asm-tree/9.7/asm-tree-9.7.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/ow2/asm/asm-util/9.7/asm-util-9.7.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/ow2/asm/asm-analysis/9.7/asm-analysis-9.7.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/minecraftforge/eventbus/6.0.5/eventbus-6.0.5.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/minecraftforge/forgespi/7.0.1/forgespi-7.0.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/minecraftforge/coremods/5.1.6/coremods-5.1.6.jar
  C:/Users/User/Desktop/UltimMC/libraries/cpw/mods/modlauncher/10.0.9/modlauncher-10.0.9.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/minecraftforge/mergetool/1.1.5/mergetool-1.1.5-api.jar
  C:/Users/User/Desktop/UltimMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  C:/Users/User/Desktop/UltimMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/jodah/typetools/0.6.3/typetools-0.6.3.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar
  C:/Users/User/Desktop/UltimMC/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/minecraftforge/fmlloader/1.20.1-47.3.0/fmlloader-1.20.1-47.3.0.jar
  C:/Users/User/Desktop/UltimMC/libraries/net/minecraftforge/fmlearlydisplay/1.20.1-47.3.0/fmlearlydisplay-1.20.1-47.3.0.jar
  C:/Users/User/Desktop/UltimMC/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar

Native libraries:
  C:/Users/User/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-windows.jar
  C:/Users/User/Desktop/UltimMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar

Mods:
  [✔️] OptiFine_1.20.1_HD_U_I6.jar
  [✔️] Patchouli-1.20.1-84-FORGE.jar
  [✔️] TerraFirmaCraft-Forge-1.20.1-3.2.7.jar

Params:
  --username hitler --version 1.20.1 --gameDir C:/Users/User/Desktop/UltimMC/instances/terra firma craft/.minecraft --assetsDir C:/Users/User/Desktop/UltimMC/assets --assetIndex 5 --uuid <PROFILE ID> --accessToken  --userType local --versionType release --launchTarget forgeclient --fml.forgeVersion 47.3.0 --fml.mcVersion 1.20.1 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230612.114412

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx9845m, -Duser.language=en, -javaagent:C:/Users/User/Desktop/UltimMC/injectors/authlib-injector-1.2.5.jar=http://127.0.0.1:51179, -Dauthlibinjector.noShowServerName]

Minecraft process ID: 14284

[authlib-injector] [INFO] Logging file: C:\Users\User\Desktop\UltimMC\instances\terra firma craft\.minecraft\authlib-injector.log
[authlib-injector] [INFO] Version: 1.2.5
[authlib-injector] [INFO] Authentication server: http://127.0.0.1:51179
[authlib-injector] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2024-10-28 00:03:25,456 main WARN Advanced terminal features are not available in this environment
[00:03:25] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, hitler, --version, 1.20.1, --gameDir, C:/Users/User/Desktop/UltimMC/instances/terra firma craft/.minecraft, --assetsDir, C:/Users/User/Desktop/UltimMC/assets, --assetIndex, 5, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, local, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.3.0, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, --width, 854, --height, 480]
[00:03:25] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.12 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[00:03:25] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[00:03:25] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[00:03:26] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[00:03:26] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.onLoad
[00:03:26] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file URL: union:/C:/Users/User/Desktop/UltimMC/instances/terra%20firma%20craft/.minecraft/mods/OptiFine_1.20.1_HD_U_I6.jar%23131!/
[00:03:26] [main/INFO] [op.OptiFineTransformationService/]: OptiFine ZIP file: C:\Users\User\Desktop\UltimMC\instances\terra firma craft\.minecraft\mods\OptiFine_1.20.1_HD_U_I6.jar
[00:03:26] [main/INFO] [op.OptiFineTransformer/]: Target.PRE_CLASS is available
[00:03:26] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: Intel(R) UHD Graphics GL version 4.6.0 - Build 31.0.101.5592, Intel
[00:03:26] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/User/Desktop/UltimMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23122!/ Service=ModLauncher Env=CLIENT
[00:03:26] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.initialize
[00:03:26] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\User\Desktop\UltimMC\libraries\net\minecraftforge\fmlcore\1.20.1-47.3.0\fmlcore-1.20.1-47.3.0.jar is missing mods.toml file
[00:03:26] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\User\Desktop\UltimMC\libraries\net\minecraftforge\javafmllanguage\1.20.1-47.3.0\javafmllanguage-1.20.1-47.3.0.jar is missing mods.toml file
[00:03:26] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\User\Desktop\UltimMC\libraries\net\minecraftforge\lowcodelanguage\1.20.1-47.3.0\lowcodelanguage-1.20.1-47.3.0.jar is missing mods.toml file
[00:03:26] [main/WARN] [ne.mi.fm.lo.mo.ModFileParser/LOADING]: Mod file C:\Users\User\Desktop\UltimMC\libraries\net\minecraftforge\mclanguage\1.20.1-47.3.0\mclanguage-1.20.1-47.3.0.jar is missing mods.toml file
[00:03:26] [main/INFO] [ne.mi.fm.lo.mo.JarInJarDependencyLocator/]: No dependencies to load found. Skipping!
[00:03:26] [main/INFO] [op.OptiFineTransformationService/]: OptiFineTransformationService.transformers
[00:03:26] [main/INFO] [op.OptiFineTransformer/]: Targets: 412
[00:03:27] [main/INFO] [op.OptiFineTransformationService/]: additionalClassesLocator: [optifine., net.optifine.]
[00:03:27] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
[00:03:27] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.20.1, --gameDir, C:\Users\User\Desktop\UltimMC\instances\terra firma craft\.minecraft, --assetsDir, C:\Users\User\Desktop\UltimMC\assets, --uuid, <PROFILE ID>, --username, hitler, --assetIndex, 5, --accessToken, ????????, --userType, local, --versionType, release, --width, 854, --height, 480]
[00:03:27] [main/WARN] [mixin/]: Error loading class: loaderCommon/forge/com/seibel/distanthorizons/common/wrappers/worldGeneration/mimicObject/ChunkLoader (java.lang.ClassNotFoundException: loaderCommon.forge.com.seibel.distanthorizons.common.wrappers.worldGeneration.mimicObject.ChunkLoader)
[00:03:28] [main/WARN] [mixin/]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/compile/pipeline/FluidRenderer (java.lang.ClassNotFoundException: me.jellysquid.mods.sodium.client.render.chunk.compile.pipeline.FluidRenderer)
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.properties.Property] with [Yggdrasil Public Key Transformer]
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:32)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	... 20 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at TRANSFORMER/patchouli@1.20.1-84-FORGE/vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.SystemReport.handler$zdf000$patchouli_addContext(SystemReport.java:516)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.SystemReport.<init>(SystemReport.java:58)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.CrashReport.<init>(CrashReport.java:34)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.CrashReport.m_127529_(CrashReport.java:346)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:149)
	... 28 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Argument modifier method getSkyColorWithColormap(Lnet/minecraft/util/CubicSampler$Vec3Fetcher;)Lnet/minecraft/util/CubicSampler$Vec3Fetcher; in tfc.mixins.json:client.ClientLevelMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap tfc.refmap.json
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 47 more
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).

**Comment by alcatrazEscapee** [comment]
This looks to be a conflict with optifine, which we do not support. Remove it.
