### ISSUE TITLE
Crash when attempting to start a fire pit with incomplete items

### ISSUE THREAD

**Issue by technostarbtd5** [TerraFirmaCraft/TerraFirmaCraft#299]
https://i.imgur.com/yRoSfo2.png
Upon trying to light a fire pit with items in the configuration seen in this image, the game experienced a crash. Here's the log:

---- Minecraft Crash Report ----

WARNING: coremods are present:
Contact their authors BEFORE contacting forge

// Daisy, daisy...

Time: 8/12/19 5:09 PM
Description: Ticking player

java.lang.NullPointerException: Ticking player
	at net.dries007.tfc.objects.items.ItemFireStarter.onUsingTick(ItemFireStarter.java:195)
	at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2670)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2090)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.dries007.tfc.objects.items.ItemFireStarter.onUsingTick(ItemFireStarter.java:195)
	at net.minecraft.entity.EntityLivingBase.func_184608_ct(EntityLivingBase.java:2670)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2090)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 54
	Entity Name: TechnostarBTD5
	Entity's Exact location: 431.10, 144.00, -501.57
	Entity's Block location: World: (431,144,-502), Chunk: (at 15,9,10 in 26,-32; contains blocks 416,0,-512 to 431,255,-497), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382)
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@3ce3336f
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8221734240 bytes (7840 MB) / 10435428352 bytes (9952 MB) up to 17179869184 bytes (16384 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx16G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 2, tallocated: 69
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 Optifine OptiFine_1.12.2_HD_U_E3 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID        | Version      | Source                                 | Signature                                |
	|:--------- |:--------- |:------------ |:-------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft | 1.12.2       | minecraft.jar                          | None                                     |
	| UCHIJAAAA | mcp       | 9.42         | minecraft.jar                          | None                                     |
	| UCHIJAAAA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2768.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge     | 14.23.5.2768 | forge-1.12.2-14.23.5.2768.jar          | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | tfc       | ${version}   | TerraFirmaCraft-MC1.12.2-0.19.1.48.jar | ee4505933cd28f4b09a0bc91007935f61e7d786e |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['TechnostarBTD5'/54, l='TFC1_48', x=431.10, y=144.00, z=-501.57]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by alcatrazEscapee** [comment]
See #295
