### ISSUE TITLE
[0.29.4.119] Null pointer @ onAttachCapabilitiesChunk

### ISSUE THREAD

**Issue by Pdan4** [TerraFirmaCraft/TerraFirmaCraft#922]
Standing around after flying around in non-tfc biome. Optifine IS installed, along with many other mods.

Booted the player.

Relevant code (CapabilityChunkData.java:36):
`[21:26:30] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.AttachCapabilitiesEvent@1472485c:
java.lang.NullPointerException: null
	at net.dries007.tfc.world.classic.chunkdata.CapabilityChunkData.onAttachCapabilitiesChunk(CapabilityChunkData.java:36) ~[CapabilityChunkData.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_696_CapabilityChunkData_onAttachCapabilitiesChunk_AttachCapabilitiesEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691) [ForgeEventFactory.class:?]
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:685) [ForgeEventFactory.class:?]
	at net.minecraft.world.chunk.Chunk.<init>(Chunk.java:94) [axw.class:?]
	at net.optifine.util.ChunkUtils.findFieldHasEntities(ChunkUtils.java:58) [ChunkUtils.class:?]
	at net.optifine.util.ChunkUtils.<clinit>(ChunkUtils.java:22) [ChunkUtils.class:?]
	at net.minecraft.client.renderer.RenderGlobal.setupTerrain(RenderGlobal.java:1405) [buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1731) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1614) [buq.class:?]
	at de.johni0702.minecraft.view.impl.client.render.ViewRenderPlan.renderSelf(ViewRenderManager.kt:424) [ViewRenderPlan.class:?]
	at de.johni0702.minecraft.view.impl.client.render.ViewRenderPlan.renderSelf(ViewRenderManager.kt:345) [ViewRenderPlan.class:?]
	at de.johni0702.minecraft.view.impl.client.render.ViewRenderPlan.render(ViewRenderManager.kt:510) [ViewRenderPlan.class:?]
	at de.johni0702.minecraft.view.impl.client.render.ViewRenderManager.renderWorld(ViewRenderManager.kt:179) [ViewRenderManager.class:?]
	at net.minecraft.client.renderer.EntityRenderer.redirect$renderWorld$zcm000(EntityRenderer.java:3738) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1385) [buq.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]`

**Comment by alcatrazEscapee** [comment]
Given the vagueness of this report, plus the fact that it's clearly optifine or another mod really breaking our assumptions about when the world exists, there's not much I can do here. I can fix the call path that NPE'd but that may have any manner of unintended side effects - if so it's not on us to fix as the world *really shouldn't be null* when attaching chunk caps.

**Comment by Pdan4** [comment]
Quite right. I appreciate the prophylactic!
